### ISSUE TITLE
The theme option is not working properly

### ISSUE THREAD

**Issue by friendsmobile** [punksta/volume_control_android#1]
# Project Information

* Repository: https://github.com/punksta/volume_control_android
* Project Name: volume_control_android
* My Github Account: https://github.com/friendsmobile

# Expected behavior

The black theme should appear when I enable the Dark theme option and the White theme should appear when I disable the option.

# Actual behavior

The theme does not change when I enable or disable  the Dark theme option

# How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=com.punksta.apps.volumecontrol) the app 
*  open the application 
*  Go down and enable and disable the Dark theme option
* Note the BUG

* Browser/App version:   Current Version1.6
* Operating system: 6.0

# Recording Of The Bug

![20190601_165514](https://user-images.githubusercontent.com/51118734/58748190-9b90e280-8429-11e9-91e6-9c0128a23df1.gif)

**Comment by punksta** [comment]
Hm, I haven't tested theme switcher on android 6.0, thanks

**Comment by punksta** [comment]
android 7.0
![Screenshot_1559398700](https://user-images.githubusercontent.com/13404754/58749660-556f6980-8491-11e9-81fe-0152dd603ab0.png)

android 6.0
![Screenshot_1559399428](https://user-images.githubusercontent.com/13404754/58749793-fad70d00-8492-11e9-8793-9d8e659d7075.png)

works well on google emulators. Must be device/manufacture specific.

could you share next information?
1) device model
2) exact os version. is that stock or custom rom?
3) is it default launcher?
4) have you faced similar issues in other apps?

**Comment by friendsmobile** [comment]
> 1. device model

SM-J710F

> 2. exact os version. is that stock or custom rom?

I cannot understand your question

> 3. is it default launcher?

YES

> 4. have you faced similar issues in other apps?

NO sir

**Comment by punksta** [comment]
https://github.com/punksta/volume_control_android/releases/tag/1.6.1
Could you try [apk](https://github.com/punksta/volume_control_android/releases/download/1.6.1/app-release.apk) from new release? You'll need to delete original app before installation.

**Comment by friendsmobile** [comment]
The latest version 1.6 does not install in my mobile phone

**Comment by punksta** [comment]
@friendsmobile can you uninstall build from google play? they are signed with different certificates.

**Comment by friendsmobile** [comment]
first, i uninstalled old  version when I install the latest version

**Comment by punksta** [comment]
I will recheck apk, thanks!

**Comment by friendsmobile** [comment]
welcome sir

**Comment by punksta** [comment]
version 2.0 should fix your problem, it should be available in google play in few hours

**Comment by friendsmobile** [comment]
thanks u sir

**Comment by punksta** [comment]
Feel free to reopen this issue if it's still not fixed. Thanks again.
