### ISSUE TITLE
Notification widget volume bar sets wrong value

### ISSUE THREAD

**Issue by punksta** [punksta/volume_control_android#14]
from google play user

media volume max is 15

1. set media volume to 10 from app
2. press the last section in notification widget
3. observe

expected volume is 15
actual volume is 14

reproducible on google pixel

**Comment by punksta** [comment]
fixed in https://github.com/punksta/volume_control_android/commit/c851c8db3514a6b922a0be9242edf082a4a41403

**Comment by Yaron10** [comment]
:+1: 
Thank you.
