### ISSUE TITLE
[Feature Request] Change profile on wifi connection

### ISSUE THREAD

**Issue by codec-abc** [punksta/volume_control_android#20]
Hi,

I don't know if it fit your vision for your app but as a user I would like to change automatically of profile on Wifi connection/disconnection.

What is your point of view on this?

**Comment by punksta** [comment]
Hi,
Good idea, I have thought about that too. I've started time based profile activation, but don't have enough time to finish it.

**Comment by punksta** [comment]
I just seen you forked the project. In case you want to build this feature: try avoid using android-x(support library) if possible, I want to keep the app as lightweight as possible

**Comment by codec-abc** [comment]
I am not very well versed into Android but aren't you missing a lot of good stuff by choosing not to use android-x?

**Comment by punksta** [comment]
last time I measured apk size with android-x, it was about 500kb. (current is 130kb)
 
I believe this is so simple app that it can work without it.

**Comment by punksta** [comment]
duplicate https://github.com/punksta/volume_control_android/issues/6
