### ISSUE TITLE
Request for daily schedule

### ISSUE THREAD

**Issue by tulliog** [punksta/volume_control_android#24]
I would really like to have a feature that allos me to change automatically the sound  profile at a given time. For example at 22:00 i d like a low-volume mode to be  activated every day. At 7:00 i'd like a high volume profile to be activated. Even better if it is a weekly schedile  which allos different settings on weekend.

**Comment by punksta** [comment]
thanks for your idea. 
https://github.com/punksta/volume_control_android/issues/6 I will keep updates here
