### ISSUE TITLE
Can't update as of newest version

### ISSUE THREAD

**Issue by pedrovay2003** [punksta/volume_control_android#27]
As of version 2.3.7, I can no longer update the app. I tried to update through both F-Droid and GitHub, but I get the same error every time. (Moto G7, Android 9.0)

![Screenshot_20200406-151645](https://user-images.githubusercontent.com/29419610/78601096-c900a680-7819-11ea-83b3-e36cae6f01af.png)

**Comment by punksta** [comment]
thanks for reporting this

**Comment by punksta** [comment]
will be fixed in next update

**Comment by pedrovay2003** [comment]
Excellent news, thank you for your work!
