### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [punksta/volume_control_android#4]
Would you mind making the APK available outside Play Store as well – for people who cannot or wantnot use that place? E.g. by attaching it to `releases/`, or bringing it to [F-Droid](https://f-droid.org/)?

**Comment by punksta** [comment]
@IzzySoft I want to release app on f-droid, just have no time for that yet. I will attach apk to releases.

**Comment by IzzySoft** [comment]
Thanks @punksta – as soon as it's there, I can pick it and serve it via [my repo](https://apt.izzysoft.de/fdroid), so please let me know when it's there.

Great to hear you'd go for the official repo! If you want, I can open an RFP for you there to see how well it goes; with some luck it's coming out straight without the need of any work on your end. Though you might wish to setup Fastlane (or Triple-T) for your app's metadata, screenshots etc (for F-Droid that's [described here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) with links to the resp. documentations) – which would also take care for your Play Store releases (so it's one point to maintain them for all "markets").

**Comment by punksta** [comment]
@IzzySoft 
I never published apps in fdroid, I want to learn the whole process. I've been using it for years and finally I have something to publish there too.
about fastlane/ci: I can do a lot :) but this app is so tiny, I just don't see reasons in setting up ci right now.

Thanks for your suggestions.

**Comment by IzzySoft** [comment]
Yeah, tiny may be and I understand CI not being needed in this context. So you might not need Fastlane for that (and not the app) – but the directory structures would allow F-Droid to pick up localizations and screenshots, for example.

As for the "full process": My article [F-Droid for advanced users and developers](https://android.izzysoft.de/articles/named/fdroid-intro-2) might give you an overoview (it's part of a series, so you might want to skim the other (currently 2) articles as well). If you have questions, don't hesitate asking (disclosure: I'm one of the F-Droid maintainers).

Glad to read you like my repo :smiley: Let me know if I shall pick your app and add it there. Integration is much faster with mine, so many apps used it to get started (and hundreds moved to the official repo afterwards). I'd just need the APK – preferably attached to its corresponding release; alternatively I also can pick it from inside the repo. Updates happen automatically within 24h of your providing a new version with APK.

**Comment by IzzySoft** [comment]
@punksta thanks for providing the APK! Your app is online now [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.punksta.apps.volumecontrol). Did you already decide on a license?

**Comment by punksta** [comment]
@IzzySoft thank you! does that apk work for you by the way?

**Comment by punksta** [comment]
damn... I forgot about licenses. it has been here for years without license. will update it

**Comment by IzzySoft** [comment]
> thank you!

:bowing_man: Gladly!

> does that apk work for you by the way?

No idea, don't need it for myself. To be honest: The only sound the speakers of my device usually make are in phone calls, not much media use. But it looked useful, and I like to promote FOSS – so I thought it's be nice to add it to my repo :grin: I urgently need to get my test device ready – I planned to at least check out apps I serve in my repo…

As for the license: Almost thoguht so :laughing: Mind telling me which one you had in mind, so I can add it to metadata while you are working to add it here?

**Comment by punksta** [comment]
I'll use MIT

**Comment by IzzySoft** [comment]
Thanks! Fixed, will become visible with the next sync (in about 11 hours).

**Comment by punksta** [comment]
thank you for your help @IzzySoft 
You are making android word better!

**Comment by punksta** [comment]
btw you know does f-droid handle app duplicates? (same package in different repos)

**Comment by punksta** [comment]
your repo link added to readme

**Comment by IzzySoft** [comment]
> does f-droid handle app duplicates? (same package in different repos)

Yes, it does. Entries are merged in the client. In "Versions" you then see which APK comes from what source. Nevertheless I usually remove apps from my repo as soon as they go live on the main repo (to avoid confusion because of signature mismatches) – and only add them (back) to mine if they cannot be updated in main anymore for some reason (e.g. build issues, dependencies).

> your repo link added to readme

Thanks, cool! If at any point you want something changed there (description update, screenshots) just ping me here. I'll stay subscribed to this issue (or `@ping` me directly in a new one, or file an issue in [my repo's tracker](https://gitlab.com/IzzyOnDroid/repo/issues) – whatever suits you best). Thanks again for your support!!! :+1:

**Comment by punksta** [comment]
@IzzySoft The app is in main fdroid repo https://f-droid.org/packages/com.punksta.apps.volumecontrol/ , thanks for you help.

**Comment by IzzySoft** [comment]
Thanks, just saw it a few hours ago – congrats! I'll remove it from my repo then (to avoid confusion for the signature mismatch). Should the need arise, I can easily re-establish it. Or add another app if you have one you want here :smile:

So until next time then!
