### ISSUE TITLE
(volume_control_android - version 2.2.0 ) The application crashes when I enable the notification widget option

### ISSUE THREAD

**Issue by friendsmobile** [punksta/volume_control_android#8]
<table class="">
 <tbody>
  <tr>
   <th scope="row">-----------------------------</a>Project Information-------------------------------------</th>
   <td>.</td>
  </tr>
  <tr>

<table class="properties">
 <tbody>
  <tr>
   <th scope="row">Project Respotry</a></th>
   <td>https://github.com/punksta/volume_control_android.</td>
  </tr>
  <tr>
   <th scope="row">Project Name:</th>
   <td>volume_control_android</a>.</td>
  </tr>
  <tr>
   <th scope="row">My Github Account</th>
   <td>  https://github.com/friendsmobile.</td>
  </tr>
  <tr>
   <th scope="row"> APK Downlod </th>
   <td> <h1><h6>https://play.google.com/store/apps/details?id=com.punksta.apps.volumecontrol.</td>
  </tr
  <tr>
   <th 
  <td> 
  </tr>
  <tr>

 </tbody>
</table>
</stope>
</end>

#### Expected behavior 

When I enable the notification widget option, the widget should appear and the application should not crash

#### Actual behavior

The application crashes when I enable the notification widget option. And the application crashes when I try to open the application twice

#### How to reproduce

* open the application
* try to enable the Notification Widget option
* Note the Error

* Browser/App version: version 2.2.0
* Operating system: 6.0

#### Recording Of The Bug

![20190705_115351](https://user-images.githubusercontent.com/51118734/60703870-b4bd0100-9eb7-11e9-9e12-4abd7e308651.gif)

#### Logcat

<pre><code>D/AndroidRuntime( 8896): Shutting down VM

E/AndroidRuntime( 8896): FATAL EXCEPTION: main

E/AndroidRuntime( 8896): Process: com.punksta.apps.volumecontrol, PID: 8896

E/AndroidRuntime( 8896): android.app.RemoteServiceException: Bad notification posted from package com.punksta.apps.volumecontrol: Couldn't create icon: StatusBarIcon(pkg=com.punksta.apps.volumecontroluser=0 id=0x7f050002 level=0 visible=true num=0 )

E/AndroidRuntime( 8896): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)

E/AndroidRuntime( 8896): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 8896): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 8896): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 8896): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 8896): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 8896): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 8896): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by punksta** [comment]
Could you kill app process(force close), update to last version and try this feature again?

**Comment by friendsmobile** [comment]
@punksta  Bug has been solved in the latest version

**Comment by punksta** [comment]
thanks for the bug report
