### ISSUE TITLE
Current procedure seems overly complicated

### ISSUE THREAD

**Issue by uli-on** [punksta/volume_control_android#9]
We currently have two independent fields with slider controls when we create profiles. Why not use the current settings, simply adjust these, and create new profiles of these settings?

Advantages: 

* No inadverted sound level surprises (by sliders being fully opened like ATM)
* Less confusing interface
* Quicker adjusting of existing settings
* Less sliders to have an eye on
* (Maybe even less code?)

**Comment by punksta** [comment]
added in https://github.com/punksta/volume_control_android/commit/841b8506cae54808d625935e108c489da1a362bb
will be delivered in next release. 

Thanks for a good idea!

**Comment by uli-on** [comment]
Thanks for integrating the idea, but this one doesn't work yet. Saving a profile does cooy over the settings, but applying such a saved profile turns up the volumes on all available sliders to full!! 

That might harm some ears, especially when trying to finetune a profile for getting to sleep, like my own attempt ;)

**Comment by punksta** [comment]
@uli-on oh no, such a annoying bug. I will sent a hot fix release today/tomorrow.

**Comment by punksta** [comment]
fixed in https://github.com/punksta/volume_control_android/releases/tag/2.2.4
